[package]
name = "leipsanon"
description = "Panic mode: selective wipe, anti-forensics, memory scrubbing"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
getrandom = { workspace = true }
log = { workspace = true }
rustix = { workspace = true }
snafu = { workspace = true }
zeroize = "1"

[lints]
workspace = true
