[package]
name = "stegnos"
description = "Encrypted storage: dm-crypt, key management, TPM sealing"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
aes = "0.8"
aes-gcm = { workspace = true }
getrandom = { workspace = true }
jiff = { workspace = true }
pbkdf2 = { workspace = true }
rustix = { workspace = true }
sha2 = { workspace = true }
snafu = { workspace = true }
log = { workspace = true }
xts-mode = "0.5"
zeroize = "1"

[lints]
workspace = true
