[package]
name = "thumos-stegnos"
description = "Encrypted storage: dm-crypt, key management, TPM sealing"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
aes = "0.8"
jiff = { workspace = true }
ring = { workspace = true }
rustix = { workspace = true }
snafu = { workspace = true }
log = { workspace = true }
xts-mode = "0.5"
zeroize = "1"
