[package]
name = "aither"
description = "WiFi driver and WPA2/3 supplicant"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
getrandom = { workspace = true }
hmac = { workspace = true }
nom = { workspace = true }
pbkdf2 = { workspace = true }
sha1 = { workspace = true }
smoltcp = { workspace = true }
snafu = { workspace = true }
log = { workspace = true }

[lints]
workspace = true
