[build]
target = "armv7a-none-eabi"

[target.armv7a-none-eabi]
rustflags = ["-C", "link-arg=-T/home/ck/aletheia/repos/thumos/crates/pyknosis-boot/link.ld"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
